name: main

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  all:
    runs-on:
    - ubuntu-latest
    steps:
      - name: Check out git repo
        uses: actions/checkout@v2
        with:
         fetch-depth: 0 # Fails with "Not a git repo" without this parameter

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - name: Install dependencies
        run: make test-deps

      - name: Run tests
        run: make run-tests
